-- Flyway baseline schema.
-- 현재 JPA 엔티티가 만드는 스키마(ddl-auto: update로 생성된 결과)를 그대로 캡처한
-- 최초 마이그레이션이다. 이후 스키마 변경은 새 버전 파일로 추가한다.

CREATE TABLE public.users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    artist_score integer,
    foodie_score integer,
    identification_code integer NOT NULL,
    nickname character varying(10) NOT NULL,
    preference_type character varying(255),
    rememberer_score integer,
    thinker_score integer,
    CONSTRAINT users_preference_type_check CHECK (((preference_type)::text = ANY ((ARRAY['THINKER'::character varying, 'FOODIE'::character varying, 'ARTIST'::character varying, 'REMEMBERER'::character varying])::text[]))),
    CONSTRAINT uk_users_nickname_identification_code UNIQUE (nickname, identification_code)
);

CREATE TABLE public.places (
    place_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    address character varying(255) NOT NULL,
    business_hours character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    description text NOT NULL,
    latitude numeric(38,2) NOT NULL,
    longitude numeric(38,2) NOT NULL,
    name character varying(255) NOT NULL,
    tags jsonb NOT NULL,
    thumbnail_url character varying(255),
    travel_mbti_type character varying(255) NOT NULL,
    CONSTRAINT places_travel_mbti_type_check CHECK (((travel_mbti_type)::text = ANY ((ARRAY['THINKER'::character varying, 'FOODIE'::character varying, 'ARTIST'::character varying, 'REMEMBERER'::character varying])::text[])))
);

CREATE TABLE public.questions (
    question_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean NOT NULL,
    content character varying(255) NOT NULL
);

CREATE TABLE public.question_options (
    question_option_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    artist_weight integer NOT NULL,
    content character varying(255) NOT NULL,
    display_order integer NOT NULL,
    foodie_weight integer NOT NULL,
    question_id bigint NOT NULL,
    rememberer_weight integer NOT NULL,
    thinker_weight integer NOT NULL,
    CONSTRAINT uk_question_options_question_display_order UNIQUE (question_id, display_order)
);

CREATE TABLE public.courses (
    course_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    ai_revision_count integer NOT NULL,
    confirmed_at timestamp(6) without time zone,
    end_date date NOT NULL,
    owner_user_id bigint NOT NULL,
    share_expires_at timestamp(6) without time zone,
    start_date date NOT NULL,
    start_time time(0) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    travel_schedule character varying(255) NOT NULL,
    CONSTRAINT courses_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying])::text[]))),
    CONSTRAINT courses_travel_schedule_check CHECK (((travel_schedule)::text = ANY ((ARRAY['DAY_TRIP'::character varying, 'ONE_NIGHT_TWO_DAYS'::character varying, 'TWO_NIGHTS_THREE_DAYS'::character varying, 'CUSTOM'::character varying])::text[])))
);

CREATE TABLE public.course_places (
    course_place_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    course_id bigint NOT NULL,
    day_number integer NOT NULL,
    estimated_stay_minutes integer NOT NULL,
    place_id bigint NOT NULL,
    travel_mode_from_previous character varying(255),
    visit_order integer NOT NULL,
    CONSTRAINT uk_course_places_course_day_order UNIQUE (course_id, day_number, visit_order),
    CONSTRAINT uk_course_places_course_place UNIQUE (course_id, place_id)
);

CREATE TABLE public.recommendation_sets (
    recommendation_set_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    disliked_place_ids jsonb NOT NULL,
    end_date date NOT NULL,
    liked_place_ids jsonb NOT NULL,
    recommended_place_ids jsonb NOT NULL,
    start_date date NOT NULL,
    travel_schedule character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT recommendation_sets_travel_schedule_check CHECK (((travel_schedule)::text = ANY ((ARRAY['DAY_TRIP'::character varying, 'ONE_NIGHT_TWO_DAYS'::character varying, 'TWO_NIGHTS_THREE_DAYS'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT uk_recommendation_sets_user UNIQUE (user_id)
);

CREATE TABLE public.explorations (
    exploration_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone,
    course_id bigint NOT NULL,
    started_at timestamp(6) without time zone,
    started_by_participant_id bigint,
    status character varying(255) NOT NULL,
    CONSTRAINT explorations_status_check CHECK (((status)::text = ANY ((ARRAY['BEFORE'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT uk_explorations_course UNIQUE (course_id)
);

CREATE TABLE public.exploration_participants (
    exploration_participant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_name character varying(255) NOT NULL,
    exploration_id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    left_at timestamp(6) without time zone,
    location_sharing_enabled boolean NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT exploration_participants_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MEMBER'::character varying])::text[]))),
    CONSTRAINT exploration_participants_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LEFT'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT uk_exploration_participants_exploration_user UNIQUE (exploration_id, user_id)
);

CREATE TABLE public.visits (
    visit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    course_place_id bigint NOT NULL,
    participant_id bigint NOT NULL,
    visited_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_visits_participant_course_place UNIQUE (participant_id, course_place_id)
);

CREATE TABLE public.visit_photos (
    visit_photo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    object_key character varying(255) NOT NULL,
    visit_id bigint NOT NULL,
    CONSTRAINT uk_visit_photos_visit_display_order UNIQUE (visit_id, display_order)
);
